### PR TITLE
Improve the rss feeds

### PR DESCRIPTION
**Pull request by Farzat07**
The current feeds miss some tags such as publish dates and proper mime types. This is an attempt to add them.

### CODE REVIEW

**Comment by Farzat07** [comment]
Actually I'm also thinking of adding the media items as html to the message content as well. Many (most?) rss readers only support video/audio links in the enclosure tag.

**Comment by knadh** [comment]
Thanks for the PR. Will review this soon.

> Actually I'm also thinking of adding the media items as html to the message content as well.

Images and polls are already rendered. Are you referring to audio and video embeds?

**Comment by Farzat07** [comment]
No actually I mean images and pdfs. My reader was unable to recognise videos and audios until I fixed the mime data, but other attachments still don't show.

**Comment by Farzat07** [comment]
I use newsboat and nextcloud news btw.

**Comment by knadh** [comment]
Ah, embedding media into the RSS feed, got it. I misread it as embedding media into the rendered HTML.

**Comment by Minoru** [comment]
@Farzat07, please note that Newsboat only displays a single enclosure, and only if it's audio or video. See https://github.com/newsboat/newsboat/blob/8c49cb9dd120991c3826f86b73c8631071d07d27/rust/libnewsboat/src/utils.rs#L324-L355 and https://github.com/newsboat/newsboat/blob/8c49cb9dd120991c3826f86b73c8631071d07d27/src/ocnewsapi.cpp#L273 for exact details.

**Comment by Farzat07** [comment]
Ok I feel the PR is ready now.

**Comment by Farzat07** [comment]
I'm starting to think that the mime and size data of the media files should actually be stored in the database.

It makes more sense to store such data than calculate it each time the site is built. Mime data is especially useful since it can be used in the decision making (for example, one can show the image itself in the rss field instead of just the thumbnail if the mime is known).

But doing this will change the database structure. How should I go about this? Past items would be missing the data but can be calculated anytime, but the question is when?

I see this can be complicated enough to call for a separate PR, but it would be nice to know whether this is on the table or not.

**Comment by knadh** [comment]
> I'm starting to think that the mime and size data of the media files should actually be stored in the database.

This should be alright, as long as tg-archive can seamlessly migrate the DB schema for existing DBs maintaining backwards compatibility.

**Comment by knadh** [comment]
Apologies for the delay in reviewing. The PR works, but two things:

1. Escaped HTML data in `<description>` should be wrapped with [`<![CDATA[ ... ]]>`](https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean) tags.
2. Since the PR introduces a new template file, `rss_template.html` which will not be present in existing installations, breaking them. To maintain backwards compatibility, I think it's better to hide functionality inside the `--rss-template` flag. If it's supplied, use the HTML template, otherwise, generate the simple description field like before.

**Comment by Farzat07** [comment]
> 1. Escaped HTML data in `<description>` should be wrapped with [`<![CDATA[ ... ]]>`](https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean) tags.

From what I saw in the answers, it seems that this tag is used when you want to include html etc WITHOUT escaping. Given that feedgen already does the escaping this shouldn't be necessary.

> 2. Since the PR introduces a new template file, `rss_template.html` which will not be present in existing installations, breaking them. To maintain backwards compatibility, I think it's better to hide functionality inside the `--rss-template` flag. If it's supplied, use the HTML template, otherwise, generate the simple description field like before.

Done.

**Comment by Farzat07** [comment]
I closed this pull request as I wanted to use my master branch for personal use. Opened a copy in #45 using a new branch.

**Comment by knadh** [comment]
Thanks. Will review and merge over the weekend.

**Pull request closed without merging**
